apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: orders-db-credentials
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "orders.labels" . | nindent 4 }}
stringData:
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ required "db.password must be set (via Terraform set_sensitive)" .Values.db.password | quote }}
